### ISSUE TITLE
PostCSS not applied to css modules that compose other css files

### ISSUE THREAD

**Issue by justinhelmer** [justinhelmer/universal-javascript-vue#8]
This doesn't work (postcss not applied):

```css
.title {
    composes: xx-large from './css/typography.css';
}
```

This does:

```css
.title {
    composes: xx-large from 'postcss-loader!./css/typography.css';
}
```
Also `import` will apply loaders, i.e.:

```js
// App.vue
import typography from './css/typography.css'
```
```css
/* App.vue */
.title {
    composes: xx-large from './css/typography.css';
}
```

But it should be baked in.

https://github.com/postcss/postcss-loader/issues/40
https://github.com/webpack-contrib/css-loader/issues/137
https://forum.vuejs.org/t/css-modules-composes-and-vue-loader/6941/3
https://github.com/css-modules/postcss-modules
